#pragma once

#include <string_view>

namespace fredpp {

/**
 * @brief Returns the FREDPP software version generated by CMake.
 *
 * @return Non-owning view of `FREDPP_VERSION_STRING`.
 *
 * @note The version source of truth is `project(... VERSION ...)` in CMake.
 * User documentation should not duplicate a hard-coded current version; the
 * running program exposes it through `?version` / `--version`.
 */
[[nodiscard]] std::string_view version() noexcept;

/**
 * @brief Returns the Git commit identity captured during CMake configuration.
 *
 * @return Seven-or-more digit hexadecimal short hash when available, otherwise
 *         the generated fallback `inconnu`.
 */
[[nodiscard]] std::string_view git_commit() noexcept;

/**
 * @brief Returns source-tree cleanliness captured during configuration.
 *
 * @return Generated value `propre`, `modifié` or `inconnu`.
 *
 * @note This describes the source tree at CMake configure time, not a live Git
 * query performed when the executable later runs.
 */
[[nodiscard]] std::string_view source_state() noexcept;

/**
 * @brief Returns the generated boolean dirty-tree flag.
 *
 * @return true when CMake recorded `FREDPP_GIT_DIRTY_VALUE != 0`.
 */
[[nodiscard]] bool source_is_dirty() noexcept;

} // namespace fredpp
