name: Build and test

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DFREDPP_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config Debug --parallel 1
      - name: Test
        run: ctest --test-dir build -C Debug --output-on-failure
